env:
  global:
  - COMMIT_AUTHOR_NAME="Travis CI"
  - COMMIT_AUTHOR_EMAIL="dolphin.w.e@gmail.com"
  - secure: svAdLkoYbHFjn/47sbkLwBYH/cB+o5kSP9Hsn7g1KMCNENO3zRMpkV57J9MrAWqThDEFJVwB4oTk9Sm/KUi3QF6J2B9l2vtc0n6EWoKDoogDP9Wg8k41EzVIu+XHEM2gr2zamDPRkJWuvM412CbnN4xXhaqeI4UkjHXaJWouI9mXttIu1JdGV/DQ/8TWyLL55FBSS0f1nDWCfrfGeQPF3aKcAIjvtPhQuwenLba+EjsOukSyp8NMVY/hpGJgQyltLijc2atPro1N+AmtBiw+EhyHtnKuu9wZ70U+v8x32HwzFgLiAS7YFGD8s9S6MlQG58J2MwkWsOA9G03k/KghfheCod4fJdEiQuaSXAAoOYW5GTCcQFCKmz6zy0EtzyhjFcSy63UzC/wH9h3zgjz38XKU7EGynUUaRNJeMJmF0Q6NeSSzblJovGa5v0XsLKcqrSEokMtLz/1yyttcizQH/hEum2exYygmm5DK+BY20J5nnpRvAsqmHDITeYvVNL/g2UXikejocirPF/GkMLCNAITnVt9ZsQGUangpguzSL8P9askuM4I/Hdvkub515GT0lh9V0P7cxEVdhxGgqCuKd6nGLVmmr0DN6noWsKc4DEk1+6i0f2vTw7nTkrtAVmtyCGaGwb0Z/1gTNOqhWjSzvi6jd2k4tzRa450MZ5ujjII=
language: node_js
node_js:
- stable
script: npm test
after_success: npm run deploy
