env:
  global:
  - secure: ldFAerFUPW25WvXXVm3VlfA46F98WW5nMk7XMU3d2T/E16wjV2aQMHBAMXwyf7kDByRDmUeTANXvA2QkOcxaSjHRpZ2OAkMg8J8otJewo5NpgyqaSTk5OU92UV4EJCDHuAYzZDI/hL4h8AB6yrH6DHAtq5LbL/Gv9ZrtE7Vh3DSw6jMMGFPsIl1ZO0n2dj5YJ43KWJbCT/VyG496kbt2UzIwprEBrPkv1MkEm/WnqA5dB3Cra+FkzNaK9ER+g9sx1Mkk5VwgaDTVesWHK6sh54gKOHTpRu0h7jUifBhfOzK1KfvVuA0uddwp2cdfuLFhC1QLCjx36ihtQt/T1S22ISTsbQURo+EYXLbmYSij99TMe0Khn83DI3a3+8mbUvX7cA+3g0dOoHILoYl3shGyVcvKOQ7tkGaqGhh9lxadYHllwfg+XJIttNFDuKCP6koXasOKF6lAtyRwqAzeSyCWZaVEZJSjpdWYJ1wWB3axcyPmcNhT+e54uaOd93iql8UFM5e7gqXTM0BcfCCzSt9SD5jceRgct+jqkV8Hvl/JIMZ129Z+YEm0+tauel1HeCqo/1A/j/Ud637ytN27TD3j9ESLRHTpu9DIHtEHCV4kJa14JCwnZ9BgTlg9CshA2oehltUITGiKeNlCTr67J2RnpHjkxDBFEL/ORqzk7pqNh+0=
language: node_js
node_js:
- stable
before_script:
- chmod +x ./scripts/deploy.sh
script: gulp copy:gh-pages
after_success: ./scripts/deploy.sh
